# vim: noexpandtab:ts=4:sw=4

provider = coldrye
os = debian
release = testing
feature = isc-dhcp-server
feature_version = 4.3.5
tag := $(shell date +"%Y%m%d%H%M%S")
image = $(os)-$(feature)

include ../../Makefile.in

